# Generated by Django 4.0.1 on 2022-01-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_publicada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='dataReceita',
            new_name='data_receita',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='modoPreparo',
            new_name='modo_preparo',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='nomeReceita',
            new_name='nome_receita',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='tempoPreparo',
            new_name='tempo_preparo',
        ),
    ]
